### ISSUE TITLE
wexbim file fails to display

### ISSUE THREAD

**Issue by davidconcertodev** [xBimTeam/XbimWebUI#4]
Hello, I am have trouble getting some wexbim files show. The link below examples one such wexbim that fails with a JavaScript throw 'Style index not found.' The file is a conversion from an IFC file which also is included in the link provided.

http://support.concertosupport.co.uk/Deane_Waitrose_Malmesbury_BuildingModel_14_2014-09-04.zip

**Comment by martin1cerny** [comment]
Hi David,
We found there was a bug in serialization code of wexbim file. Could you try it again with the very latest code from debug branch please? Or you can reference it from [myget repository](https://www.myget.org/f/xbimtest) where we publish prerelease nuget packages as we go.

Let me know if this helps please.

Martin

**Comment by davidconcertodev** [comment]
Hi Martin. Thank you for your help. That particular IFC does now display in the xbim-viewer after converting to wexbim using the updated libraries. However there are some other IFC files that still do not display with the same JavaScript exception. An odd thing is that these other IFC files that I have yet to post did briefly successfully convert to wexbim just today. But not anymore. Was it a transient Nuget update? I will post them here as soon as I get permission to make them available.

**Comment by martin1cerny** [comment]
This is interesting. It certainly wasn't a transient update. If you send
the files we can have a look on that. Thank you very much for discovering
remaining bugs in the tool. I hope we have them all fixed soon.

Martin

2015-02-23 18:44 GMT+01:00 David Horrocks <notifications@github.com>:

**Comment by davidconcertodev** [comment]
Hi Martin,
http://support.concertosupport.co.uk/14-218_Malmesbury-COLLABORATED-WCEC_STAND_14.zip

Here is another somewhat larger IFC file which I am unable to reliably convert to wexbim. Sometimes this file will convert using XbimGeometry v3.0.7. A successful conversion may depend on what had been converted before. This is odd because a “fresh” new Xbim class object is created for each IFC file. An unsuccessful conversion may either produce a file that fails to load in the viewer or may fail with a memory access violation or may get stuck in a loop that seems never to finish. The latest Nuget XbimGeometry v3.0.9 seems to get stuck in a loop in geomContext.CreateContext(XbimGeometryType.PolyhedronBinary). 
Here is the Visual Studio 2013 source for the converter which is implemented as a Windows desktop application. 
https://github.com/davidconcertodev/BimConvert.git

A 64 bit compile is needed for large IFC files due to large RAM usage. BimConvert with this IFC file may use anywhere from 3.5 GB to 6 GB RAM depending on which version of the XbimGeometry and XbimEssentials is used. My guess is that many .NET GC based allocations are using up RAM. There is an intermittent memory access violation which I have yet to reproduce with full source debugging of the libraries. 

The BimConvert GUI uses a separate thread for the conversion and permits cancellation on a granularity of completed files. You have to wait for the current file to finish (if ever) before the cancel takes effect.  A more instantaneous cancel needs library support with perhaps the use of a fast volatile memory Boolean cancel check occurring within the inner most loops. Long IO calls may need the something like WaitAny with a ManualResetEvent cancel plus the relevant IO completion object.

Hope this sheds some light on things.

Regards,
David

**Comment by martin1cerny** [comment]
Hi David,

I'm sorry for delayed reply. We were getting everything together for 
tomorrow presentation of our project on Ecobuild. If there is an endless 
loop in XbimGeometry it is the best to ask Steve Lockley as this is his 
child :-) The conversion is resource intensive because it runs in 
multiple threads and it performs loads of geometric operations. There is 
also Xbim.Exchange command line application as a new comer to 
XbimExchange. This also does the conversion from IFC to wexbim and JSON. 
We use this for our current development and debugging. Could you try 
this? It would be the closest to our core environment.

I'm sorry but I won't be able to try your files until next week. Let me 
know if anything changes please.

Martin

Dne 26.2.2015 v 18:00 David Horrocks napsal(a):

**Comment by davidconcertodev** [comment]
Hi Martin,
Thank you for you reply. I have just today Git pulled the latest master of Xbim.Exchange and performed a default Any CPU debug build. I then opened a 64 bit console window and ran a batch file that I called xbc.bat  which contained this text:
"C:\Users\david.horrocks\Documents\Visual Studio 2013\Projects\xBimTeam\XbimExchange\Xbim.Exchange\bin\Debug\Xbim.Exchange.exe" %1

I then ran:
 xbc 14-218_Malmesbury-COLLABORATED-WCEC_STAND_14.ifc
I received a failure that is consistence with my own custom BimConvert project though I see that Xbim.Exchange contains some additional calls. See the attach picture below.

![xbim exchange stopped](https://cloud.githubusercontent.com/assets/10993661/6461239/d66d0ccc-c195-11e4-8794-a8c1fa1020d7.PNG)

Regards,
David

**Comment by davidconcertodev** [comment]
Hi Martrin,
I have built pure x64 build. I have left it converting the same file and it is still processing. Here is a screen shot after more than 10 minutes of processing.

![xbim exchange 10min](https://cloud.githubusercontent.com/assets/10993661/6462123/46501c8e-c19e-11e4-826d-045d1f0ee002.PNG)

**Comment by martin1cerny** [comment]
Well, is means that the IFC file is not a valid IFC2x3. Which SW was used
to create the file?
Dne 3. 3. 2015 13:10 "David Horrocks" <notifications@github.com> napsal(a):

**Comment by SteveLockley** [comment]
I have had a long look at this as I was worried about the performance times. xBIM has been designed for server deployment so has a low memory footprint. It turns out there are two problems. Firstly, I introduced a minor bug in the translation to GitHub which had major ramifications. IDispose was incorrectly implemented on the new Geometry interface causing no garbage collection to occur. This has been resolved. Secondly, the update to OCC introduced a bug on the OCC front with meshing which causes a tail recursion on models with large meshes. The OCC meshing has been replaced with LibMeshDotNet for these situations. All in all the application is faster and smoother, I am recursion testing at the moment and will commit shortly

**Comment by davidconcertodev** [comment]
Hi Martin, 
I cannot confirm the IFC2x3 compliance though I have been told that the drawing is produced by Revit.

Regards,
David

**Comment by davidconcertodev** [comment]
Hi Steve, 
That sounds great. I look forward to a test drive. The company I work for has moved me another project so I can look only in my own time. 

A suggestion for improvement would be to support a cross thread cancel for long running calls. This would be needed if one wanted to host the conversion process in a Windows service. Windows services must compile with a timely shutdown (90 seconds max, I think) to avoid being disabled by the system. 

Regards,
David

**Comment by martin1cerny** [comment]
Hi @davidconcertodev ,

can I close this issue?

**Comment by davidconcertodev** [comment]
Close it.

**Comment by PetarMetodiev** [comment]
Hello,

I am getting the same  'Style index not found.' error in the browser console. I am using XbimExcahnge (Nuget Stable Release Build 3.1.10)command line tool to convert my ifc files to wexbim. I have tried couple of different ifc files and none seem to work. I am following the hello building tutorial, not doing anything extraordinary.

Any help will be appreciated
Thanks!

**Comment by martin1cerny** [comment]
Hi @PetarMetodiev,

please make sure you use the latest version of both XbimExchange and XbimWebUI. There was a bug where wexBIM file got slightly changed but it was not signalized in the version number so viewer read wrong data which results in 'Style index not found' which is basically check of consistency. But it is fixed in the latest versions.

Martin

**Comment by PetarMetodiev** [comment]
Thanks for the quick response!

I just pulled the master branches from both XbimExchange and XbimWebUI and I still get the same error.

**Comment by martin1cerny** [comment]
Once in pulling could you try to do the same with develop branches? I believe the change I mentioned did already make it to master branch but it is not under my control. XbimExchange needs to reference XbimGeometry 3.1.12.

**Comment by PetarMetodiev** [comment]
It works now. Thank you for the quick reaction and sorry for the late response.
